### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/GrocerEZ#4]
Once the feature list #2 is decided, we should be able to begin determining what data we want to store in the database and how we want to store it. I've created a [draw.io](https://drive.google.com/file/d/1FM2rcxsWdDjcm305Z6Z1gpsBgz8IIQg4/view?usp=sharing) sketch that we can use to diagram out what fields each object type will have and the realtions between them. You might not be able to edit it until I share it with you, so just request access and I'll aprrove y'all.

**Comment by firejake308** [comment]
Okay, so I figured out how to edit the diagram. After clicking the link above, you have to press `Open with` and then diagrams.net. After giving permission to diagrams.net to use your Google account, you should be good to go

**Comment by adg516** [comment]
I added some fields to the databases that I thought would be useful as well as more specific data types that we can use. Here is a complete list for reference when we get to implementation: https://www.postgresql.org/docs/9.5/datatype.html As far as storing images go, our solutions include using _blob_ (binary large object), using a separate database with _DBlink_, or using _bytea_ (byte array). I'm not really sure about the specifics of these tools as I've never used them but there is some more detail here: https://stackoverflow.com/questions/54500/storing-images-in-postgresql Each solution has their advantages so this could be another task in the near future. I'm not 100% solidified on that database design but it looks workable as of right now. Let me know if you have any more comments or concerns and we can talk about it
